refactor: Move zellij functions to zshalias
Move `openZellij` function, its keybinding, and associated helper functions (`current_dir`, `change_tab_title`, `set_tab_to_working_dir`) and zsh hooks from `.zshrc` to `zshalias`.

diff --git a/zsh/.config/zsh/zshalias b/zsh/.config/zsh/zshalias
--- a/zsh/.config/zsh/zshalias
+++ b/zsh/.config/zsh/zshalias
@@ -18,3 +18,49 @@ alias -g NUL='>/dev/null 2>&1' # pipe standard output and error to /dev/null
 alias -g C='| wl-copy'
 alias -g P='wl-paste'
 alias -g L='| less'
+
+# keybindings
+openZellij() {
+   # zellij <$TTY
+   dotfiles-zellij-f
+   zle redisplay
+}
+zle -N openZellij
+bindkey "^z" openZellij
+
+function current_dir() {
+   local current_dir=$PWD
+   if [[ $current_dir == $HOME ]]; then
+      current_dir="~"
+   else
+      current_dir=${current_dir##*/}
+   fi
+
+   echo $current_dir
+}
+
+function change_tab_title() {
+   local title=$1
+   command nohup zellij action rename-tab $title >/dev/null 2>&1
+}
+
+function set_tab_to_working_dir() {
+   local result=$?
+   local title=$(current_dir)
+   # uncomment the following to show the exit code after a failed command
+   # if [[ $result -gt 0 ]]; then
+   #     title="$title [$result]"
+   # fi
+
+   change_tab_title $title
+}
+
+# function set_tab_to_command_line() {
+#     local cmdline=$1
+#     change_tab_title $cmdline
+# }
+
+if [[ -n $ZELLIJ ]]; then
+   add-zsh-hook precmd set_tab_to_working_dir
+   # add-zsh-hook preexec set_tab_to_command_line
+fi
